#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    # See MacOS install
    #STOW_FOLDERS="bin,tmux"
    STOW_FOLDERS="z,zsh,nvim"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/clean-env
