#!/usr/bin/env zsh

if [[ -z $STOW_FOLDERS ]]; then
    # See MacOS install
    #STOW_FOLDERS="bin,nvim,tmux,z,zsh"
    STOW_FOLDERS="z,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/clean-env
