require('user.commenter')
require('user.lsp-colors')
require('user.lsp-installer')
require('user.treesitter')
require('user.telescope')
require('user.nvim-tree')
require('user.lualine')
require('user.toggleterm')
