-- local M = {}
--
-- config =
--
-- function M.setup()
--     local status_ok, alpha = pcall(require, "alpha")
--     if not status_ok then
--         return
--     end
--     alpha.setup(config)
-- end
--
--
-- return M
